export default {
  created_date: 'created_date',
  modified_date: 'modified_date',
  hotel_name: 'hotel_name',
  status: 'confirmation_status',
  confirm_number: 'confirmation_number',
  confirm_date: 'confirmation_date',
  cancel_date: 'cancellation_date',
};

const x = {
  chain_name: 'hotel_name',
  chain_id: '5301',
  hotel_id: '45623',
  sap_id: '975178',
  description: 'GDS Reservations',
  channel: 'GDS',
  secondary_source: 'Amadeus',
  sub_source: 'Amadeus',
  sub_source_code: '1A',
  user_login: null,
  cancel_number: null,
  guest_first_name: 'LOUIS',
  guest_last_name: 'LETERRIER',
  arrival_date: '26 Jul 2016',
  depart_date: '27 Jul 2016',
  rate_category_name: 'Negotiated',
  rate_category_code: 'NEG',
  rate_type_name: 'Sony BB Rate',
  rate_type_code: 'SON13',
  room_type_name: 'Deluxe Room',
  room_type_code: 'CLD',
  nights: '1',
  adr: '160.8991',
  rooms: '1',
  reservation_revenue: '160.8991',
  currency: 'EUR',
  loyalty_points_payment: 'No',
  travel_industry_id: '20247194',
  travel_agency_name: 'AMERICAN EXPRESS VOYAGES',
  travel_agency_street_address: '400 AVENUE ROUMANILLE QUARTIER DES TEMPLIERS',
  travel_agency_city: 'BIOT',
  travel_agency_state: 'FR',
  travel_agency_zip_postal_code: '06410',
  travel_agency_country: 'FR',
  total_dynamic_package_revenue: '0.0000',
  share_with: 'No',
  itinerary_number: '5301B2494650',
  commissionable_percent: null,
  noncredited_cancellation: ' ',
  profile_type_selection: 'Other',
  original_room_type_name: '',
  original_room_type_code: '',
  room_upsell: 'N',
  market_segment_code: null,
  salutation: null,
  guest_country: null,
  template_name: null,
  shell_name: null,
  template_code: null,
  channel_connect_confirm_number: null,
  market_source_code: null,
};
